Allow multiple .md to be specified for md2rfc

diff --git a/bin/md2rfc b/bin/md2rfc
--- a/bin/md2rfc
+++ b/bin/md2rfc
@@ -3,18 +3,27 @@
 # This script will invoke mmark to convert markdown to xml2rfc format,
 # then it will invoke xml2rfc to produce an outout text file
 #
-# The name of the .md file (with the .md extension) is expected as the first
-# argument.
+# One may specify one or more markdown files (with the .md extension).
 #
 
-MDFILE=$1
-XMLFILE=$(echo $MDFILE | sed 's/\.md$/.xml/')
-TXTFILE=$(echo $MDFILE | sed 's/\.md$/.txt/')
-
-if [ x"$MDFILE" == x"$XMLFILE" ] ; then
-    echo "usage: md2rfc <draft_name.md>"
+# Ensure that at least one file was specified
+if [ $# -eq 0 ] ; then
+    echo "usage: md2rfc <draft_name.md> [<draft_name.md> ...]"
     exit 1;
-else
-    mmark -xml2 -page "$MDFILE" "$XMLFILE" && \
-      xml2rfc --text "$XMLFILE" -o "$TXTFILE"
 fi
+
+# Loop through all of the specified .md files to produce .txt files as output
+while [ $# -gt 0 ] ; do
+    MDFILE=$1
+    shift
+    XMLFILE=$(echo $MDFILE | sed 's/\.md$/.xml/')
+    TXTFILE=$(echo $MDFILE | sed 's/\.md$/.txt/')
+
+    if [ x"$MDFILE" == x"$XMLFILE" ] ; then
+        echo "Error: $MDFILE is not a .md file"
+        exit 1
+    else
+        mmark -xml2 -page "$MDFILE" "$XMLFILE" && \
+          xml2rfc --text "$XMLFILE" -o "$TXTFILE"
+    fi
+done
